### ISSUE TITLE
Autocompletion doesn't work

### ISSUE THREAD

**Issue by jamesthompson** [sublimescala/sublime-ensime#33]
m6 branch : Autocompletion doesn't work. There's no API results coming back when I type a period after a variable. 

Is this being implemented, or is it a straightforward bug? This is the one thing I need to switch to ENSIME / SUBLIME / SBT from intelliJ!

This project is awesome, please keep up the excellent coding.

**Comment by rorygraves** [comment]
should be working in https://github.com/ensime/ensime-sublime
