### ISSUE TITLE
Go to definition rarely works

### ISSUE THREAD

**Issue by velvia** [sublimescala/sublime-ensime#59]
First of all, thanks for your work on this.  I love Sublime and am hoping to make it my main editor.

"Go to definition" seems to rarely work.   So far, it works on
- Traits within my own project

However, it doesn't seem to work on much else.  The following fails with "Cannot locate symbol"...
- Traits in dependencies (eg Akka, spray, etc.)  (here it says "cannot locate spray.routing.xxxx"
- variables
- methods, even in the same class

**Comment by rorygraves** [comment]
I think this is working better now https://github.com/ensime/ensime-sublime
