### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by felipehummel** [sublimescala/sublime-ensime#70]
Hi, after enabling ENSIME in sublime text, the whole sublime experience has been slowing down. Even simply typing code somethings is slow.

I'm running on a MacBook Pro 13" i5 with 8GB RAM. I've increased the heap for ENSIME from 1500MB to 2500MB but the lags are still occurring, specially when I'm typing code.

Any ideas?

**Comment by rorygraves** [comment]
I have not seen a performance issue on the updated plugin  - closing - please reopen on https://github.com/ensime/ensime-sublime if you see it again
