### ISSUE TITLE
“Ensime: Startup” fails with `[Errno 8] Exec format error`

### ISSUE THREAD

**Issue by soc** [sublimescala/sublime-ensime#71]
This is what the console reports:

    [Errno 8] Exec format error
    [cmd:  [u'sbt', u'-Dsbt.log.noformat=true', u'ensime generate']]
    [dir:  /home/soc/Entwicklung/spire]
    [path: /home/soc/.bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]
    [Finished]

The sbt shelll script and the sbt-launcher.jar are both in ~/.bin. Invoking sbt manually works without issues.

**Comment by tiomke** [comment]
same here

**Comment by rorygraves** [comment]
Please try the updated plugin https://github.com/ensime/ensime-sublime  and open a ticket there if you see the issue

Thanks

Rory
