### ISSUE TITLE
Automatic run of ensime generate did not work

### ISSUE THREAD

**Issue by nelsonblaha** [sublimescala/sublime-ensime#72]
(OSX)

I Added the following to plugins.sbt:
// Ensime for Sublime Text 2 compiler connection
addSbtPlugin("org.ensime" % "ensime-sbt-cmd" % "0.1.1")

I then ran Ensime: startup in Sublime Text 2, resulting in an apparent successful automatic setup. Although the plugin claimed to write the configuration to .ensime, the file was unchanged. By entering sbt in the terminal and manually running ensime generate, I was able to fill out .ensime, and then everything worked normally.

**Comment by rorygraves** [comment]
Thanks @samijaber - OSX is a bit funny about user/global paths.
