### ISSUE TITLE
Are there supposed to be auto-suggestions?

### ISSUE THREAD

**Issue by derekchiang** [sublimescala/sublime-ensime#74]
Hello,

First of all, thank you very much for this awesome work!

I was wondering if auto-suggestion is supposed to be a feature?  I mean, when I type in an identifier and type ".", should I expect to see a list of suggestions pop up, including the methods/fields of that identifier?

This issue might be similar to this one: https://github.com/sublimescala/sublime-ensime/issues/33

Currently, when I type ".", nothing shows up at all.  Nothing shows up when I press "ctrl + space" either.

I'm using Ubuntu + Sublime 2 + Scala 2.10.  I have already installed Ensime.  I can start it up with no problem.  Error highlighting is also working.

Thank you for your time!

Best,
Derek

**Comment by rorygraves** [comment]
Resolved.
