### ISSUE TITLE
Ensime validation is not triggered on save of file

### ISSUE THREAD

**Issue by rubymaniac** [sublimescala/sublime-ensime#77]
There is an issue with my sublime-ensime installation and the ensime validation triggering. I have installed it via the Package Manager and then I added a Main.scala file with an error inside

```scala
import org.slf4j._

object Main
  def main(args: Array[String]) = {
    val logger: Logger = LoggerFactory.getLogger("Logger");
    logger.info("Main here")
  }
}
```

following [this tutorial](http://blog.hugeaim.com/2012/03/22/use-sublime-text-2-for-scala-development/). I then saved the file (the ensime server was up) and had no error highlighting! The only time I got some error highlighting is when I tried `Ensime: Add Import` to import a package. I think something is happening with the Ensime validation when I save a file. 

I am using Sublime Text 2.0.1 and the ensime server: ensime_2.10.0-0.9.8.9.tar.gz and I am on a mac.

**Comment by rorygraves** [comment]
I have not seen this under the updated plugin  - closing - please reopen on https://github.com/ensime/ensime-sublime if you see it again
