### ISSUE TITLE
handover to ensime organisation

### ISSUE THREAD

**Issue by fommil** [sublimescala/sublime-ensime#99]
Hi! There was a lot of interest at Scala Days about getting ENSIME working on sublime again. I think it would be a lot easier for everybody coming to ENSIME to find the active repo at the top of the fork tree. Would you please be able to hand over ownership to the ensime organisation? We'll add you as an admin to the repo (along with a few others).

Just go into settings to do this.

**Comment by VladUreche** [comment]
Hi Sam! Both @xeno-by and myself are swamped with our own projects to a point where we're not able to maintain sublime-ensime at all. From my side I would be glad to hand over the organization to someone who has the time and motivation to maintain it. We did have an earlier attempt to do so, but it failed :disappointed: 

@xeno-by, are you comfortable with this?

**Comment by fommil** [comment]
@VladUreche cool! I spoke to Eugene at Scala Days and he seemed to be quite happy that dev was picking up again. We're very keen for him **NOT** to get involved because it means `scala.meta` will be slowed down and we're all extremely keen to get it :stuck_out_tongue: 

@rorygraves you might need to rebase in a moment

**Comment by fommil** [comment]
oh hold on, this isn't the top of the tree. I'll ask the top tree owner.

**Comment by fommil** [comment]
let's wait for @casualjim to respond, that would be a better solution.

**Comment by xeno-by** [comment]
@fommil @VladUreche I definitely don't mind. In fact, it would be extremely cool to transfer this repo to someone who's going to actively maintain it.

**Comment by fommil** [comment]
Looks like casualjim is going to handover the top repo :smile: so that's probably the best solution. Once we have all the commits from here (the active repo) in the ensime repo, we'll either send a PR to previous repos with directions or maybe just close this one down to avoid confusion?

You're all welcome to be admins on the new repo, btw! Just ask.

**Comment by VladUreche** [comment]
Great to hear you've taken over @fommil! :+1: :four_leaf_clover:

**Comment by fommil** [comment]
Oh, I've not. @dickwall promised :-P

**Comment by VladUreche** [comment]
Either way, it's glad to hear scala-ensime will finally get some love :)

**Comment by fommil** [comment]
cool, this is now complete! There are loads of open tickets on your repo but since we're effectively starting with a clean sheet, I'm sure everything important will pop up again on the ensime organisation.

Would you rather keep this `sublimescala` organisation alive and get PRs to point to the active dev community, or just remove it?

I've added you with write access to the repo at the `ensime` organisation.

**Comment by rorygraves** [comment]
@VladUreche  @xeno-by I would suggest immediately deleting these repos:

https://github.com/sublimescala/ensime-sbt-cmd
https://github.com/sublimescala/ensime
https://github.com/sublimescala/sublimescala.github.com

I will submit a PR tomorrow to put a redirect banner for the main repo (as its indexed by google etc.)

**Comment by xeno-by** [comment]
I don't mind. @VladUreche ?

**Comment by VladUreche** [comment]
Nothing against it if @xeno-by agrees.

**Comment by VladUreche** [comment]
@rorygraves @fommil @dickwall -- I forked all three repos before removing them, in case you remember you wanted something. I will delete them now.

**Comment by rorygraves** [comment]
Completed.
